# Generated by Django 2.2.3 on 2019-12-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Слаг')),
                ('body', models.TextField(blank=True, db_index=True, verbose_name='Пост')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='Blog.Tag', verbose_name='Тэги')),
            ],
            options={
                'ordering': ['-date_pub'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('body', models.TextField(blank=True, db_index=True, verbose_name='Комментарий')),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog.Post', verbose_name='Пост')),
            ],
            options={
                'ordering': ['-date_pub'],
            },
        ),
    ]
